spring:
  application:
    name: ReminderApp

  # PostgreSQL
  config:
    import: optional:classpath:application-secret-localhost.yml

  # JPA, Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml