spring:
  application:
    name: ReminderApp

  # PostgreSQL
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA, Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # logging
  logging:
    level:
      com.example.reminderapp.controller: DEBUG
      com.example.reminderapp.service: DEBUG

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENTID}
            clientSecret: ${GOOGLE_CLIENTSECRET}
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile